<a href="https://colab.research.google.com/github/AsitSrivastava06/NumPy/blob/main/Experiment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment-8
## TITLE: Tools in EDA - Numpy Pandas
### NAME: ASIT SRIVASTAVA
#### BATCH:A2
#### PRN:25070123026

In [ ]:
#Declaration of Numpy
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Dimension of Array
print(a.ndim)
print(b.ndim)


1
2


In [ ]:
print(a.shape) # how many elements in 1D
print(b.shape) # how many rows & columns in 2D

(4,)
(2, 3)


In [ ]:
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
#In Built funcions using numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
c= a*2
d=a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [ ]:
print(a)
print(a+5)

[10 20 30 40]
[15 25 35 45]


In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.max(a)

np.int64(40)

In [ ]:
np.min(a)

np.int64(10)

In [ ]:
np.sum(a)

np.int64(100)